# Generated by Django 4.2.2 on 2023-08-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shorturl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invalidmal', models.CharField(max_length=50)),
                ('comment', models.TimeField()),
            ],
        ),
    ]
