# Generated by Django 4.2.2 on 2023-08-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_reportmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmessage',
            name='comment',
            field=models.CharField(max_length=100),
        ),
    ]
