# Generated by Django 4.2.2 on 2023-08-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_reportmessage_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmessage',
            name='comment',
            field=models.TextField(max_length=100),
        ),
    ]
